### ISSUE TITLE
Kernel dies after donwloading the Teuk_amps_a0.0_lmax_10_nmax_30_new.h5

### ISSUE THREAD

**Issue by Hassankh92** [BlackHolePerturbationToolkit/FastEMRIWaveforms#55] opened 2022-07-20 20:16 UTC
If I load SlowSchwarzschildEccentricFlux, the kernel dies after that. After that, it would not work even for fast waveform unless I delete the Teuk_amps_a0.0_lmax_10_nmax_30_new.h5 file and do not load the slow waveform model again.

**Comment by lorenzsp** [comment] 2022-07-26 13:45
Hi Hassan, I tried to load and use SlowSchwarzschildEccentricFlux and it seems to be working fine. Could you post an example or clarify what the issue is?

**Comment by mikekatz04** [comment] 2022-08-22 17:21
I am closing this now with no movement. If it is still an issue, please reopen it.

**Closed by mikekatz04** 2022-08-22 17:21 UTC
